---
title: "Logistic_v4"
author: "Eileen Zhang"
date: "11/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
```


```{r}
# Load in all raw data sets
book <- read.csv("book.csv")
book.test <- read.csv("booktest.csv")
book.train <- read.csv("booktrain.csv")
orders <- read.csv("ordersall.csv", stringsAsFactors = F)
```

```{r}
# Add respond column to indicate if a customer responded to promotion
#book$respond <- ifelse(book$logtargamt > 0, 1, 0)
# Drop empty malformat column
book.train$X <- NULL
# Orders with orddate as Date and net as total price of order
orders$orddate <- lubridate::dmy(orders$orddate)
# Outlier: orders > 1000
orders = orders[-which(orders$qty > 1000),]
orders$net <- orders$qty * orders$price
# Orders of customers who respond to promotion
orders.responders <- book.train %>% 
  filter(logtargamt > 0) %>%
  merge(orders, by = 'id')
# All information about the customers in training set
book.train.merge <- merge(book.train, book, by = 'id')
book.train.merge$logtargamt.y <- NULL
book.train.merge <- rename(book.train.merge, logtargamt = logtargamt.x)
book.train.merge$respond <- ifelse(book.train.merge$logtargamt > 0, 1, 0)
# All information about customers in training set with addition of avgNetOrder
book.train.full <- orders %>% 
  group_by(id) %>% 
  #could try sum(net) to see difference
  summarise(avgNetOrder = mean(net),totalqty = sum(qty) ) %>%
  merge(book.train.merge, by = 'id') 
```

```{r}
#head(book.train.full, 25)
```

```{r}
train_final = book.train.full[,c(1:8, 69)]
colnames(train_final) = c("ID", "AvgCost", "TotalQty", "logtargamt", "Recency", "Frequency", "Amount", "Time", "Respond")
train_final$AvgCost = round(train_final$AvgCost, 2)
train_final$Amount = round(train_final$Amount, 2)
train_final$Respond = as.factor(train_final$Respond)
summary(train_final)
#head(train_final, 10)
```

```{r}
##outlier detection
mod1_logistic = glm(Respond ~ AvgCost + TotalQty + Recency + Frequency + Amount + Time, data = train_final, family = binomial)
summary(mod1_logistic)
train_final = train_final[-which(cooks.distance(mod1_logistic)>qf(0.1,6,8218)),]
##in total delete 6 outliers
```

```{r}
##Multicolinearity
source("panelfxns.R")
pairs(train_final[, -1], upper.panel = panel.smooth, lower.panel = panel.cor, cex.labels=1.3)
cor1 = cor(train_final[,c(2:3,4:7)])
diag(solve(cor1))
##No VIF is higher than 10
```

```{r}
prob1 = ifelse(train_final$Respond == 0, 0.85/(length(which(train_final$Respond == 0))), 0.15/(length(which(train_final$Respond == 1))))
train_final_rep = train_final[sample(c(1:nrow(train_final)), replace = TRUE, prob = prob1),]
length(which(train_final_rep$Respond == 1))
```

```{r}
mod2_logistic = glm(Respond ~ AvgCost + TotalQty + Recency + Frequency + Amount + Time, data = train_final_rep, family = binomial)
summary(mod2_logistic)
mod3_logistic = glm(Respond ~ AvgCost + Recency + Frequency + Time, data = train_final_rep, family = binomial)
summary(mod3_logistic)
```

##Added data variable

```{r}
new_book <- book[!is.na(book$logtargamt),]
new_book <- subset(new_book, select = c(id, logtargamt, recency, frequency, amount, tof))
new_book$after <- ifelse(new_book$logtargamt > 0, 1, 0)
new_book$ordersPer <-  new_book$frequency / new_book$tof
new_book$amountPer <- new_book$amount/ new_book$tof
result2 <- orders %>%
  group_by(id, orddate) %>%
  summarise(sum(qty))
orders1 <- orders[which(orders$qty<1000), ]
mergedOrdersBook <- merge(new_book, orders1, by="id")
startDate <- "01-Aug-14"
ndate1 <- as.Date(startDate, "%d-%B-%y")
mergedOrdersBook$orddate <- as.Date(mergedOrdersBook$orddate , "%d-%B-%y")
mergedOrdersBook$dateDiff <- as.numeric(difftime(ndate1, mergedOrdersBook$orddate), units="days")
mergedOrdersBook$oneMonth <- ifelse(mergedOrdersBook$dateDiff < 31 , 1, 0)
mergedOrdersBook$threeMonth <- ifelse(mergedOrdersBook$dateDiff < 63 & mergedOrdersBook$dateDiff >31, 1, 0)
mergedOrdersBook$sixMonth <- ifelse(mergedOrdersBook$dateDiff > 63 & mergedOrdersBook$dateDiff <183 , 1, 0)
mergedOrdersBook$oneYr <- ifelse(mergedOrdersBook$dateDiff > 182 & mergedOrdersBook$dateDiff < 365 , 1, 0)
mergedOrdersBook$twoYr <- ifelse(mergedOrdersBook$dateDiff > 365 & mergedOrdersBook$dateDiff < 730 , 1, 0)
mergedOrdersBook$pastTwo <-  ifelse(mergedOrdersBook$dateDiff > 730 , 1, 0)
df <- aggregate(mergedOrdersBook$qty, by=list(id=mergedOrdersBook$id), FUN=sum)
mergedOrdersBook <- merge(mergedOrdersBook, df, by="id")
result <- mergedOrdersBook %>%
  group_by(id) %>%
  summarise_all(funs(max))
colnames(result)[1] = "ID"
final = merge(train_final, result[,c(1,17:22)], by = "ID")
```

```{r}
summary(glm(Respond ~ AvgCost + TotalQty + Recency + Frequency + Amount + Time + oneYr +oneMonth + threeMonth+sixMonth, data = final, family = binomial))
prob2 = ifelse(final$Respond == 0, 0.85/(length(which(final$Respond == 0))), 0.15/(length(which(final$Respond == 1))))
train_final_rep1 = final[sample(c(1:nrow(final)), replace = TRUE, prob = prob2),]
summary(glm(Respond ~ AvgCost  + Recency + Frequency  + Time +oneMonth + threeMonth+sixMonth + twoYr + pastTwo, data = train_final_rep1, family = binomial))
```