---
title: "PA_Project_2"
author: "Chuan Du (Sophie)"
date: "11/17/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
```

```{r}
# Load in all raw data sets
book <- read.csv("book.csv")
book.test <- read.csv("booktest.csv")
book.train <- read.csv("booktrain.csv")
orders <- read.csv("ordersall.csv", stringsAsFactors = F)
```

```{r}
# Add respond column to indicate if a customer responded to promotion
#book$respond <- ifelse(book$logtargamt > 0, 1, 0)

# Drop empty malformat column
book.train$X <- NULL

# Orders with orddate as Date and net as total price of order
orders$orddate <- lubridate::dmy(orders$orddate)
orders$net <- orders$qty * orders$price

# Orders of customers who respond to promotion
orders.responders <- book.train %>% 
  filter(logtargamt > 0) %>%
  merge(orders, by = 'id')

# All information about the customers in training set
book.train.merge <- merge(book.train, book, by = 'id')
book.train.merge$logtargamt.y <- NULL
book.train.merge <- rename(book.train.merge, logtargamt = logtargamt.x)
book.train.merge$respond <- ifelse(book.train.merge$logtargamt > 0, 1, 0)

# All information about customers in training set with addition of avgNetOrder
book.train.full <- orders %>% 
  group_by(id) %>% 
  #could try sum(net) to see difference
  summarise(avgNetOrder = mean(net)) %>%
  merge(book.train.merge, by = 'id')
```

```{r}
head(book.train.full, 25)
```

```{r}
train_final = book.train.full[c(1:7, 68)]
colnames(train_final) = c("ID", "AvgCost", "logtargamt", "Recency", "Frequency", "Amount", "Time", "Respond")
train_final$AvgCost = round(train_final$AvgCost, 2)
train_final$Amount = round(train_final$Amount, 2)
train_final$Respond = as.factor(train_final$Respond)
#head(train_final, 10)
```

### Outlier Detections

```{r}
#repeated part for running
train_final = book.train.full[c(1:7, 68)]
colnames(train_final) = c("ID", "AvgCost", "logtargamt", "Recency", "Frequency", "Amount", "Time", "Respond")
train_final$AvgCost = round(train_final$AvgCost, 2)
train_final$Amount = round(train_final$Amount, 2)
train_final$Respond = as.factor(train_final$Respond)

#avgcost
train_final1 = subset(train_final, train_final$AvgCost >= mean(train_final$AvgCost) - 3*sd(train_final$AvgCost) & train_final$AvgCost <= mean(train_final$AvgCost) +3*sd(train_final$AvgCost))

#recency
train_final2 = subset(train_final1, train_final1$Recency >= mean(train_final1$Recency) - 3*sd(train_final1$Recency) & train_final1$Recency <= mean(train_final1$Recency) +3*sd(train_final1$Recency))

#frequency
train_final3 = subset(train_final2, train_final2$Frequency >= mean(train_final2$Frequency) - 3*sd(train_final2$Frequency) & train_final2$Frequency <= mean(train_final2$Frequency) +3*sd(train_final2$Frequency))

#amount
train_final4 = subset(train_final3, train_final3$Amount >= mean(train_final3$Amount) - 3*sd(train_final3$Amount) & train_final3$Amount <= mean(train_final3$Amount) +3*sd(train_final3$Amount))

#refine final train
train_final = train_final4
```

```{r}
summary(train_final) 
```


```{r}
source("panelfxns.R")
pairs(train_final[, -1], upper.panel = panel.smooth, lower.panel = panel.cor, cex.labels=1.3)
```

```{r}
mod1_logistic = glm(Respond ~ AvgCost + Recency + Frequency + Amount + Time, data = train_final, family = binomial)
summary(mod1_logistic)
```

Amount is the most non-significant predictor, so we first remove it.

```{r}
mod2_logistic = glm(Respond ~ AvgCost + Recency + Frequency + Time, data = train_final, family = binomial)
summary(mod2_logistic)
```

Average Cost is the most non-significant predictor, so we then remove it.

```{r}
mod3_logistic = glm(Respond ~ Recency + Frequency + Time, data = train_final, family = binomial)
summary(mod3_logistic)
```



### Data Cleaning for Testing Data


```{r}
# Add respond column to indicate if a customer responded to promotion
book$respond <- ifelse(book$logtargamt > 0, 1, 0)

# Drop empty malformat column
book.test$X <- NULL

# Orders with orddate as Date and net as total price of order
orders$orddate <- lubridate::dmy(orders$orddate)
orders$net <- orders$qty * orders$price

# Orders of customers who respond to promotion
orders.responders <- book.test %>% 
  filter(logtargamt > 0) %>%
  merge(orders, by = 'id')

# All information about the customers in training set
book.test.merge <- merge(book.test, book, by = 'id')
book.test.merge$logtargamt.y <- NULL
book.test.merge <- rename(book.test.merge, logtargamt = logtargamt.x)
book.test.merge$respond <- ifelse(book.test.merge$logtargamt > 0, 1, 0)

# All information about customers in training set with addition of avgNetOrder
book.test.full <- orders %>% 
  group_by(id) %>% 
  #could try sum(net) to see difference
  summarise(avgNetOrder = mean(net)) %>%
  merge(book.test.merge, by = 'id')
```

```{r}
head(book.test.full, 25)
```

```{r}
test_final = book.test.full[c(1:7, 68)]
colnames(test_final) = c("ID", "AvgCost", "logtargamt", "Recency", "Frequency", "Amount", "Time", "Respond")
test_final$AvgCost = round(test_final$AvgCost, 2)
test_final$Amount = round(test_final$Amount, 2)
test_final$Respond = as.factor(test_final$Respond)
head(test_final, 10)
```

```{r}
predicted = predict(mod3_logistic, test_final, type = "response")
```

```{r}
SSE_test1 = sum((as.numeric(test_final$Respond) - predicted)^2); SSE_test1
```









