---
title: "Linear Model - Sophie’s clean"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
orders <- read_csv("/Users/tovasimonson/Documents/MSIA/Fall2018/PA/Project/ordersall.csv")
test <- read_csv("/Users/tovasimonson/Documents/MSIA/Fall2018/PA/Project/booktest.csv")
book <- read_csv("/Users/tovasimonson/Documents/MSIA/Fall2018/PA/Project/book.csv")
train <- read_csv("/Users/tovasimonson/Documents/MSIA/Fall2018/PA/Project/booktrain.csv")
```

```{r}
bookTrain <- book[!is.na(book$logtargamt),]
bookTrain <- subset(bookTrain, select = c(id, logtargamt, recency, frequency, amount, tof))
bookTrain$after <- ifelse(bookTrain$logtargamt > 0, 1, 0)
bookTrain$ordersPer <-  bookTrain$frequency / bookTrain$tof
bookTrain$amountPer <- bookTrain$amount/ bookTrain$tof
bookTrain$af <- bookTrain$amount * bookTrain$frequency
bookTrain$rf <- bookTrain$recency * bookTrain$frequency
merBookTRAIN<- merge(bookTrain, train, by="id")
merBookTRAIN <- merBookTRAIN[, -12]
```


```{r}
ordersTRAIN <- orders[which(orders$qty<1000), ]
ordersTRAIN$net <- ordersTRAIN$qty * ordersTRAIN$price
ordersTRAIN$returned <- ifelse(ordersTRAIN$price== 0, 1, 0)
mergOrdersBookTRAIN <- merge(merBookTRAIN, orders1, by="id")

startDate <- "01-Aug-14"
ndate1 <- as.Date(startDate, "%d-%B-%y")
mergOrdersBookTRAIN$orddate <- as.Date(mergOrdersBookTRAIN$orddate , "%d-%B-%y")
mergOrdersBookTRAIN$dateDiff <- as.numeric(difftime(ndate1, mergOrdersBookTRAIN$orddate), units="days")
mergOrdersBookTRAIN$oneMonth <- ifelse(mergOrdersBookTRAIN$dateDiff < 31 , 1, 0)
mergOrdersBookTRAIN$threeMonth <- ifelse(mergOrdersBookTRAIN$dateDiff < 63 & mergOrdersBookTRAIN$dateDiff >31, 1, 0)
mergOrdersBookTRAIN$sixMonth <- ifelse(mergOrdersBookTRAIN$dateDiff > 63 & mergOrdersBookTRAIN$dateDiff <183 , 1, 0)
mergOrdersBookTRAIN$oneYr <- ifelse(mergOrdersBookTRAIN$dateDiff > 182 & mergOrdersBookTRAIN$dateDiff < 365 , 1, 0)
mergOrdersBookTRAIN$twoYr <- ifelse(mergOrdersBookTRAIN$dateDiff > 365 & mergOrdersBookTRAIN$dateDiff < 730 , 1, 0)
mergOrdersBookTRAIN$pastTwo <-  ifelse(mergOrdersBookTRAIN$dateDiff > 730 , 1, 0)
```


```{r}
finalLogisticTRAIN<- ordersTRAIN %>% 
  group_by(id) %>% 
  summarise(avgNetOrder = mean(net),totalqty = sum(qty) ) %>%
  merge(mergOrdersBookTRAIN, by = 'id') 
```

```{r}
train_final1 = subset(finalLogisticTRAIN, finalLogisticTRAIN$avgNetOrder >= mean(finalLogisticTRAIN$avgNetOrder) - 3*sd(finalLogisticTRAIN$avgNetOrder) & finalLogisticTRAIN$avgNetOrder <= mean(finalLogisticTRAIN$avgNetOrder) +3*sd(finalLogisticTRAIN$avgNetOrder))
#recency
train_final2 = subset(train_final1, train_final1$recency >= mean(train_final1$recency) - 3*sd(train_final1$recency) & train_final1$recency <= mean(train_final1$recency) +3*sd(train_final1$recency))
#frequency
train_final3 = subset(train_final2, train_final2$frequency >= mean(train_final2$frequency) - 3*sd(train_final2$frequency) & train_final2$frequency <= mean(train_final2$frequency) +3*sd(train_final2$frequency))
#amount
train_final4 = subset(train_final3, train_final3$amount >= mean(train_final3$amount) - 3*sd(train_final3$amount) & train_final3$amount <= mean(train_final3$amount) +3*sd(train_final3$amount))
#totalqty
train_final5 = subset(train_final4, train_final4$totalqty >= mean(train_final4$totalqty) - 3*sd(train_final4$totalqty) & train_final4$totalqty <= mean(train_final4$totalqty) +3*sd(train_final4$totalqty))
#refine final train
train_final = train_final5
result <- train_final %>%
  group_by(id) %>%
  summarise_all(funs(max))
result
```


```{r}
result <- train_final %>%
  group_by(id) %>%
  summarise_all(funs(max))
result
```



```{r}
mod1_logistic <- glm(after ~ avgNetOrder + totalqty + recency + frequency + amount + tof, data = result, family = binomial)
summary(mod1_logistic)
```


```{r}
baselineLOG <- glm(after ~ recency + frequency  + tof  + af + amountPer + threeMonth  + twoYr , data=result, family= binomial)
summary(baselineLOG)

```

