---
title: "Project1"
author: "Eileen Zhang"
date: "11/15/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
book = read.csv("book.csv", header = T)
order = read.csv("ordersall.csv", header = T)

summary(book$recency)
summary(book$frequency)
summary(book$amount)
summary(book$tof)
hist(book$recency, col = "grey")
hist(book$frequency, col = "grey")
hist(book$amount, col = "grey")
hist(book$tof, col = "grey")


order$cat = factor(order$category, 
                   levels =c(1,3,5,6,7,8,9,10,12,14,17,19,20,21,22,23,
                             26,27,30,31,35,36,37,38,39,40,41,44,50,99), 
                   labels = c("fiction","classics","cartoons", "legends","philosophy", "religion",
                              "psychology","linguistics", "art","music", "artreprints", "history",
                              "contemporary history", "economy", "politics", "science", "computer
                              science", "traffic", "maps", "travel guides", "health", "cooking",
                              "learning", "games", "sports", "hobbies", "nature/animals/plants",
                              "encyclopedias", "videos", "non-books"))
summary(order$cat)
summary(order$qty)
ggplot(data = order) + geom_bar(aes(x = factor(1), fill = order$cat)) + 
  coord_polar(theta = "y") + ggtitle("Book Category") +
  labs(x = "", y = "") 
```